### PR TITLE
The features squad has a designer!!!

### PR DESCRIPTION
**Pull request by rachelhathaway**
@mattwondra :smile_cat: 

I know someone who's interested in applying for the Product Manager position, and in our chatting, I ended up here...

### CODE REVIEW

**Comment by mattwondra** [comment]
@rachelhathaway Yay! Can you also update the team breakdown in that same line? (e.g. 9 people, 2 designers). I don't think I can because this PR is coming from a private fork.

**Comment by rachelhathaway** [comment]
Went ahead and non-juniorized myself as well...

**Comment by mattwondra** [comment]
noice :shipit:

**Comment by rachelhathaway** [comment]
@mattwondra Do you know how to give me write access? I don't have it, that's the only reason I opened a PR.

**Comment by mattwondra** [comment]
DORP

Yeah just gave it to the whole team. I forget that new repos in the org don't default to giving full access to the Developers group

**Comment by rachelhathaway** [comment]
:+1: @mattwondra

**Pull request merged**
